version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: # docker-compose.yml 경로
        target: /compose
      - type: bind
        source: # config.yaml 경로
        target: /config
      - type: bind
        source: # db 경로 
        target: /videos/data
      - type: bind
        source: # 비디오 경로 1
        target: /videos/movies
      - type: bind
        source: # 비디오 경로 2
        target: /videos/others
    environment:
      - PORT=8000
      - CONFIG_PATH=/config/config.container.yaml
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
